# Deploy Docs
# This workflow will build and deploy the docs to Firebase Hosting

name: Deploy Docs
on: 
  push:
    branches:
      - master

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        run: npm install -g pnpm
      - run: pnpm install && pnpm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STEAM_BREW }}
          expires: 3d
          projectId: steam-brew
          channelId: 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'