# Deploy Docs
# This workflow will build and deploy the docs to Firebase Hosting

name: Deploy Docs
on: 
  push:
    branches:
      - master

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        run: npm install -g pnpm
      - run: pnpm install && pnpm run build
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          pnpm setup
          pnpm install -g firebase-tools && firebase deploy --only hosting --token $FIREBASE_TOKEN